# Generated by Django 5.0 on 2023-12-20 11:15

import autoslug.fields
import django.db.models.deletion
import restaurant
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('desc', models.TextField(max_length=4096)),
                ('slug', autoslug.fields.AutoSlugField(editable=True, populate_from='name', slugify=restaurant.models.russian_slugify, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('name', models.CharField(max_length=32)),
                ('desc', models.TextField(max_length=4096)),
                ('slug', autoslug.fields.AutoSlugField(editable=True, populate_from='name', slugify=restaurant.models.russian_slugify, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
